// List of engaging, knowledge-rich quiz topics with public domain images/logos (Wikimedia/Unsplash/Pexels)
// Each topic has: { key, title, image, imageAttribution }

const quizTopics = [
  {
    key: 'ai_future',
    title: 'The Future of AI',
    emoji: '🤖',
    role: 'student',
    difficulty: 'medium',
    num_questions: 15,
  },
  {
    key: 'space_exploration',
    title: 'Space Exploration',
    emoji: '🚀',
    role: 'student',
    difficulty: 'medium',
    num_questions: 15,
  },
  {
    key: 'world_history',
    title: 'World History',
    emoji: '🌍',
    role: 'student',
    difficulty: 'medium',
    num_questions: 15,
  },
  {
    key: 'music_legends',
    title: 'Music Legends',
    emoji: '🎵',
    role: 'student',
    difficulty: 'medium',
    num_questions: 15,
  },
  {
    key: 'modern_tech',
    title: 'Modern Technology',
    emoji: '💻',
    role: 'student',
    difficulty: 'medium',
    num_questions: 15,
  },
  {
    key: 'nature_wonders',
    title: 'Natural Wonders',
    emoji: '🏞️',
    role: 'student',
    difficulty: 'medium',
    num_questions: 15,
  },
  {
    key: 'sports_moments',
    title: 'Iconic Sports Moments',
    emoji: '🏅',
    role: 'student',
    difficulty: 'medium',
    num_questions: 15,
  },
  {
    key: 'world_cuisine',
    title: 'World Cuisine',
    emoji: '🍲',
    role: 'student',
    difficulty: 'medium',
    num_questions: 15,
  },
  {
    key: 'cinema_classics',
    title: 'Cinema Classics',
    emoji: '🎬',
    role: 'student',
    difficulty: 'medium',
    num_questions: 15,
  },
  {
    key: 'world_geography',
    title: 'World Geography',
    emoji: '🗺️',
    role: 'student',
    difficulty: 'medium',
    num_questions: 15,
  },
  {
    key: 'inventions',
    title: 'Great Inventions',
    emoji: '💡',
    role: 'student',
    difficulty: 'medium',
    num_questions: 15,
  },
  {
    key: 'mythology',
    title: 'World Mythology',
    emoji: '⚡',
    role: 'student',
    difficulty: 'medium',
    num_questions: 15,
  },
  {
    key: 'famous_art',
    title: 'Famous Artworks',
    emoji: '🖼️',
    role: 'student',
    difficulty: 'medium',
    num_questions: 15,
  },
  {
    key: 'wildlife',
    title: 'Wildlife & Animals',
    emoji: '🐾',
    role: 'student',
    difficulty: 'medium',
    num_questions: 15,
  },
  {
    key: 'world_languages',
    title: 'World Languages',
    emoji: '🗣️',
    role: 'student',
    difficulty: 'medium',
    num_questions: 15,
  },
  {
    key: 'space_science',
    title: 'Space & Astronomy',
    emoji: '🌌',
    role: 'student',
    difficulty: 'medium',
    num_questions: 15,
  },
  {
    key: 'internet',
    title: 'The Internet',
    emoji: '🌐',
    role: 'student',
    difficulty: 'medium',
    num_questions: 15,
  },
  {
    key: 'global_culture',
    title: 'Global Cultures',
    emoji: '🎎',
    role: 'student',
    difficulty: 'medium',
    num_questions: 15,
  },
  {
    key: 'famous_people',
    title: 'Famous People',
    emoji: '👤',
    role: 'student',
    difficulty: 'medium',
    num_questions: 15,
  },
  {
    key: 'health_science',
    title: 'Health & Medicine',
    emoji: '🩺',
    role: 'student',
    difficulty: 'medium',
    num_questions: 15,
  },
  {
    key: 'environment',
    title: 'Environment & Climate',
    emoji: '🌳',
    role: 'student',
    difficulty: 'medium',
    num_questions: 15,
  },
  {
    key: 'innovation',
    title: 'Innovation & Startups',
    emoji: '🚀',
    role: 'student',
    difficulty: 'medium',
    num_questions: 15,
  },
  {
    key: 'literature',
    title: 'World Literature',
    emoji: '📚',
    role: 'student',
    difficulty: 'medium',
    num_questions: 15,
  },
  {
    key: 'politics',
    title: 'World Politics',
    emoji: '🏛️',
    role: 'student',
    difficulty: 'medium',
    num_questions: 15,
  },
  {
    key: 'transport',
    title: 'Transport & Travel',
    emoji: '✈️',
    role: 'student',
    difficulty: 'medium',
    num_questions: 15,
  },
  {
    key: 'fashion',
    title: 'Fashion & Style',
    emoji: '👗',
    role: 'student',
    difficulty: 'medium',
    num_questions: 15,
  },
  {
    key: 'food_science',
    title: 'Food Science',
    emoji: '🥗',
    role: 'student',
    difficulty: 'medium',
    num_questions: 15,
  },
  {
    key: 'video_games',
    title: 'Video Games & Esports',
    emoji: '🎮',
    role: 'student',
    difficulty: 'medium',
    num_questions: 15,
  },
  {
    key: 'robotics',
    title: 'Robotics',
    emoji: '🤖',
    role: 'student',
    difficulty: 'medium',
    num_questions: 15,
  },
  {
    key: 'philosophy',
    title: 'Philosophy',
    emoji: '🧠',
    role: 'student',
    difficulty: 'medium',
    num_questions: 15,
  }
  // Add more topics as desired
];

export default quizTopics;
